config/routes.rb
Rails.application.routes.draw do
  root "departments#index"
  
  resources :departments do
    resources :items
  end
  
  resources :items do
    resources :comments
    resources :ratings
  end

end

app/models/add_avatar_to_department.rb
class AddAvatarToDepartment < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :item
end

app/models/department.rb
class Department < ApplicationRecord
  has_many :items

  def self.alphebetical_order
    order(:name)
  end
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :department
  has_many :comments
  has_many :ratings

  def average_rating
    
    average = 0
    count = 0
    self.ratings.each do |rating|
      # binding.pry
      average += rating[:value]
      count += 1
    end
    # binding.pry
    return average = (average / count)
    # /length(item.ratings)
  end
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :item

  # def average_rating(item)
    
  #   average = 0
  #   count = 0
  #   item.ratings.each do |rating|
  #     # binding.pry
  #     average += rating[:value]
  #     count += 1
  #   end
  #   # binding.pry
  #   return average = (average / count)
  #   # /length(item.ratings)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_item
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  
  def index
    @comments = @item.comments
  end

  def show
    # binding.pry

  end

  def new
    @comment = @item.comments.new
    render partial: "form"
  end

  def create
    @comment = @item.comments.new(comment_params)

    # binding.pry
    if @comment.save
      # redirect_to comment_comment_path(@item @comment)
      redirect_to item_comment_path(@item, @comment)
    else
      render :new
    end
  end

  def edit
    render partial: "form"
  end

  def update
    if @comment.update(comment_params)
      redirect_to item_comment_path(@item, @comment)
    else
      render :edit
    end
  end

  def destroy
    @comment.destroy
    # binding.pry
    redirect_to department_item_path([@item[:department_id],@item[:id]]) # need the comment param to link the id
  end
    
#############################################  
private

  def comment_params
    params.require(:comment).permit(:title, :body, :author)
  end

  def set_item
    # binding.pry
    @item = Item.find(params[:item_id])
  end

  # def set_comment
  #   # binding.pry
  #   @comment = comment.find(params[:comment_id])
  # end

  def set_comment
    @comment = Comment.find(params[:id])
  end
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  # Only runs this action before the listed methods
  before_action :set_department, only: [:show, :edit, :update, :destroy]
  # Could also run as an ^except: [:index, :new, :create]

  def index
    @departments = Department.all.alphebetical_order
    # render :index #rails does this in the background
  end

  def show
    # localhost:3000/departments/1
  end

  def new
    @department = Department.new
    render partial: "form"
  end

  def create
    @department = Department.new(department_params)
    binding.pry
    if @department.save
      redirect_to departments_path
    else
      # nice to add error messages here
      render :new
    end
  end

  def edit
    render partial: "form"
  end

  def update
    if @department.update(department_params)
      redirect_to department_path(@department)
    else  
      # nice to add error messages here
      render :edit
    end
  end

  def destroy
    @department.destroy
    redirect_to departments_path
  end

  private

  def department_params
    params.require(:department).permit(:name, :description, :avatar)
  end

  def set_department
    
    @department = Department.find(params[:id])
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_department
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  
  def index
    @items = @department.items
  end

  def show
  end

  def new
    @item = @department.items.new
    render partial: "form"
  end

  def create
    @item = @department.items.new(item_params)

    # binding.pry
    if @item.save
      # redirect_to department_item_path(@department, @item)
      redirect_to department_item_path(@department,@item)
    else
      render :new
    end
  end

  def edit
    render partial: "form"
  end

  def update
    if @item.update(item_params)
      redirect_to department_path(@department)
    else
      render :edit
    end
  end

  def destroy
    @item.destroy
    # binding.pry
    redirect_to department_path(@department) # need the department param to link the id
  end
    
#############################################  
private

  def item_params
    params.require(:item).permit(:name, :description, :price)
    # binding.pry
  end

  def set_department
    # binding.pry
    @department = Department.find(params[:department_id])
  end

  def set_item
    # binding.pry
    @item = Item.find(params[:id])
  end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  before_action :set_item
  before_action :set_rating, only: [:show, :edit, :update, :destroy]
  
  def index
    @ratings = @item.ratings
    # @average_rating = Rating.average_rating(@item)
  end

  def show
    # binding.pry
   
  end

  def new
    @rating = @item.ratings.new
    render partial: "form"
  end

  def create
    @rating = @item.ratings.new(rating_params)

    # binding.pry
    if @rating.save
      # redirect_to comment_comment_path(@item @comment)
      redirect_to item_rating_path(@item, @rating)
    else
      render :new
    end
  end

  def edit
    render partial: "form"
  end

  def update
    if @rating.update(rating_params)
      redirect_to item_comment_path(@item, @rating)
    else
      render :edit
    end
  end

  def destroy
    @rating.destroy
    # binding.pry
    redirect_to department_item_path([@item[:department_id],@item[:id]]) # need the comment param to link the id
  end

  def show_ratings
    binding.pry
    @item.average_rating
  end
    
#############################################  
private

  def rating_params
    params.require(:rating).permit(:value)
  end

  def set_item
    # binding.pry
    @item = Item.find(params[:item_id])
  end

  # def set_comment
  #   # binding.pry
  #   @comment = comment.find(params[:comment_id])
  # end

  def set_rating
    @rating = Rating.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/views/comments/_form.html.erb
<h1><%= @item.id ? 'Edit Comment' : 'Create Comment' %></h1>
<hr />
<%= form_for [@item, @comment] do |f| %>
  <%= f.label :author %>
  <%= f.text_field :author %>
  <br />
  <%= f.label :title %>
  <%= f.text_field :title, required: true, autofocus: true %>
  <br />
  <%= f.label :body %>
  <%= f.text_area :body %>
  <br />
  <br />
  <%= f.submit %>
<% end %>

app/views/comments/index.html.erb
<h1> <%= @item.name %> </h1>
<hr />
<ul>
  <% @comment.each do |comment| %>
    <li> <%= link_to comment.title, comment %> </li>
    <body> - <%= comment.author %> </body>
  <% end %>
</ul>
<hr />
<%= link_to 'Create a new comment', new_comment_path %>

app/views/comments/show.html.erb
<h1> <%= @comment.title %> </h1> 
<body> Author: <%= @comment.author %> </body> 
<br />
<body> Added on: <%= @comment.created_at %> </body>
<hr />
<body> <%= @comment.body %> </body> 
<hr />
<%= link_to 'Edit Comment', edit_item_comment_path([@item, @comment]) %>
<br />
<%= link_to 'Delete Comment', [@item, @comment], method: :delete %>
<br />
<%= link_to 'Back to Items', department_item_path(@item[:department_id], @item[:id]) %>

app/views/departments/_form.html.erb
<h1><%= @department.id ? 'Edit Department' : 'Create Department' %></h1>
<hr />
<%= form_for @department do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>
  <br />
  <%= f.label :description %>
  <%= f.text_area :description %>
  <br />
  <%= f.label :avatar %>
  <%= f.text_field :avatar, required: true, placeholder: "Avatar" %>
  <br />
  <br />
  <%= f.submit %>
<% end %>

app/views/departments/index.html.erb
<h1 class="ui header">Departments</h1>
<table class="ui striped table">
  <thead>
    <tr class="center aligned">
      <th colspan="4"></th>
    </tr>
  </thead>
  
  <% @departments.each do |department| %>
    <tbody>
      <tr class="center aligned">
        <td>
          <h3> <%= department.name %> </h3>
          <div class="image">
          <img class="ui avatar image small" src="https://robohash.org/<%= department.avatar %>?set=set4" />
          </div>
        </td>

        <td><%= link_to "Show", department_path(department) %></td>
        <td><%= link_to "Edit", edit_department_path(department) %></td>
        <td><%= link_to "Delete", department_path(department), method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br />
<%= link_to "New Department", new_department_path %>

app/views/departments/show.html.erb
<h1> <%= @department.name %> Department</h1>
<h4> <%= @department.description %> </h4>
<hr />
<ul>
  <% @department.items.each do |item| %>
    <li><%= link_to item.name, [@department, item] %></li>
  <% end %>
</ul>
<%= link_to 'Create a New Item', new_department_item_path(@department) %>
<%# <%= link_to 'View Items', department_item_path(@department) %>
<%# <br />  %>
<hr />
<%# <p>What would you like to do?</p> %>
<%= link_to 'Edit Department', edit_department_path(@department) %>
<br />
<%= link_to 'Delete Department', @department, method: :delete %>
<br />
<%= link_to 'Back to All Departments', departments_path %>

<div class="ui card">
  <div class="image">
    <img class="ui avatar image large" src="https://robohash.org/<%= @department.avatar %>?set=set4" />
  </div>
  <div class="content">
    <p class="header">
      <%= @department.name %> Department
      <%# <%= @department.description %> 
    </p>
    <div>
      <%=@department.description%>
    </div>
    <div class="description">
      <span class="date"> <%=@department.created_at%> </span>
    </div>
    <br />
    <div class="extra content">
      <%= link_to 'Edit', edit_department_path(@department), class: "ui button yellow" %>
      <%= link_to 'Delete', @department, method: :delete, class: "ui button red" %>
    </div>
  </div>
 </div> 

app/views/items/_form.html.erb
<h1><%= @item.id ? 'Edit Item' : 'Create Item' %></h1>
<hr />
<%= form_for [@department, @item] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>
  <br />
  <%= f.label :description %>
  <%= f.text_area :description %>
  <br />
  <%= f.label :price %> $
  <%= f.text_field :price %>
  <br />
  <br />
  <%= f.submit %>
<% end %>

app/views/items/show.html.erb
<h1> <%= @item.name %> </h1> 
<h4> Description: <%= @item.description %> </h4> 
<h4> Price: $<%= @item.price %> </h4>
<hr />
<%# <h2> Ratings </h2> %>
<%# <%= binding.pry > %>
<h3> Average Rating: <%= @item.average_rating %> </h3>
<%= link_to 'Add New Rating', new_item_rating_path(@item) %>
<br />
<%= link_to 'View All Ratings', item_ratings_path(@item) %>
<hr />
<h3> Comments </h3>
<ul>
  <% @item.comments.each do |comment| %>
    <%# <%= binding.pry %>
    <li> <%= link_to comment.title, [@item, comment] %> </li>
    <body> - <%= comment.author %> </body>
  <% end %>
</ul>
<%= link_to 'Add Comment', new_item_comment_path(@item) %>
<hr />
<%= link_to 'Edit Item', edit_department_item_path([@department, @item]) %>
<br />
<%= link_to 'Delete Item', [@department, @item], method: :delete %>
<br />
<%= link_to 'Back to Items', department_path(@department) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DepartmentStore</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %> 
  </head>

  <body>
    <div class="ui container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/ratings/_form.html.erb
<h1><%= @item.id ? 'Edit Item' : 'Create Item' %></h1>
<hr />
<%= form_for [@item, @rating] do |f| %>
  <%= f.label 'Rating (0-5 stars)' %>
  <%= f.text_field :value, required: true, autofocus: true %>
  <%# <br />
  <%= f.label :body%>
  <%# <%= f.text_area :body %> 
  <br />
  <br />
  <%= f.submit %>
<% end %>

app/views/ratings/delete.html.erb
<h1>Ratings#delete</h1>
<p>Find me in app/views/ratings/delete.html.erb</p>

app/views/ratings/edit.html.erb
<h1>Ratings#edit</h1>
<p>Find me in app/views/ratings/edit.html.erb</p>

app/views/ratings/index.html.erb
<h1>All Ratings for <%= @item.name %> </h1>
<hr />
<h4> Average Rating: <%= @item.average_rating %> </h4>
<hr />
<ul>
  <% @ratings.each do |rating| %>
    <li> <%= rating.value %> stars </li>
    <body> - Submitted on: <%= rating.created_at %> </body>
    <br />
  <% end %>
</ul>
<%= link_to 'Back to Items', department_item_path(@item[:department_id], @item[:id]) %>

app/views/ratings/new.html.erb
<h1>Ratings#new</h1>
<p>Find me in app/views/ratings/new.html.erb</p>

app/views/ratings/show.html.erb
<h1> <%= @item.name %> </h1> 
<h4> Your Rating: <%= @rating.value %> stars </h4> 
<h4> Date: <%= @rating.created_at %> </h4>
<hr />

<%= link_to 'Edit Rating', edit_item_rating_path([@item, @rating]) %>
<br />
<%= link_to 'Delete Rating', [@item, @rating], method: :delete %>
<br />
<%= link_to 'Back to Items', department_item_path(@item[:department_id], @item[:id]) %>